name: "Dev-Agent Demo"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-dev-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
      
      - name: Run Dev Agent on self
        id: dev-agent
        uses: ./
        with:
          test-command: "pytest tests/test_sanity.py --maxfail=1 -v"
          max-iterations: "2"
          auto-pr: "false"
          git-branch-prefix: "demo/dev-agent-fix"
        continue-on-error: true
      
      - name: Report results
        run: |
          echo "Dev Agent completed with status: ${{ steps.dev-agent.outputs.success }}"
          if [ "${{ steps.dev-agent.outputs.iterations-used }}" != "" ]; then
            echo "Iterations used: ${{ steps.dev-agent.outputs.iterations-used }}"
          fi
          if [ "${{ steps.dev-agent.outputs.branch-created }}" != "" ]; then
            echo "Branch created: ${{ steps.dev-agent.outputs.branch-created }}"
          fi
          if [ "${{ steps.dev-agent.outputs.pr-url }}" != "" ]; then
            echo "PR created: ${{ steps.dev-agent.outputs.pr-url }}"
          fi
